---
- hosts: all
  become: yes
  tasks: 
#### execute shell script & print the output
    - name : execute a shell
      script: /tmp/test.sh
      register: abc
    - debug:
         msg: "{{ abc.stdout_lines }}"
#### execute a normal shell command 
    - name : execute a command
      command: echo " executing a command"
#### create a files
    - name: restart a service 
      shell: touch "{{ item }}"
      loop: 
        - "naresh.txt"
        - "new.java"
