---
- hosts: 172.31.1.203
  become: yes
  tasks:
   - name: Install Java 1.8
     apt: 
      name: openjdk-8-jdk 
      state: present
   - name: add group "tomcat"
     group: 
      name: tomcat
   - name: add user "tomcat"
     user: 
      name: tomcat 
      group: tomcat 
   - name: Download Tomcat
     get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
   - name: Extract archive
     command: /bin/tar xvf /opt/apache-tomcat-8.5.54.tar.gz -C /opt
   - name: create tomcat home
     command: mv /opt/apache-tomcat-8.5.54 /opt/tomcat 
   - name: Change ownership of Tomcat installation
     file: 
      path: /opt/tomcat 
      owner: tomcat 
      group: tomcat 
      mode: 0755 
      state: directory 
      recurse: yes
      #   - name: Deploy Applicaiton
      #     copy:
      #      src: /tmp/sampleapp.war
      #      dest: /opt/tomcat/webapps
   - name: Start Tomcat
     command: "nohup /opt/tomcat/bin/startup.sh"
     become_user: tomcat
