apiVersion: apps/v1
kind: Deployment
metadata:
   name: test-deployment
spec:
   replicas: 3
   selector:
     matchLabels:
        app: testapp
   template:
     metadata:
        name: testpod
        labels:
          app: testapp
     spec:
       containers:
         - name: tomcat
           image: tomcat
           ports:
             - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
   - protocol: TCP
     port: 8080
